- src/components/main/teamPageBtn/TeamPageBtn.jsx
- src/components/main/teamPageBtn/style.jsx
- src/components/team/teamNav/TeamNav.jsx
- src/components/team/teamNav/style.jsx
- src/components/team/teamNavMember/TeamNavMember.jsx
- src/components/team/teamNavMember/style.jsx
- src/components/team/teamPageHeader/TeamPageHeader.jsx
- src/components/team/teamPageHeader/style.jsx
- src/pages/main/Main.jsx
- src/pages/main/style.jsx
- src/pages/team/Team.jsx
- src/pages/team/style.jsx
- src/router.jsx
팀 페이지 제작과 페이지의 상단, 사이드바 컴포넌트 제작
메인페이지에서 팀 상세로 가는 경로와 그에 따른 라우터 수정
> 팀페이지 구현과 메인 페이지,라우터 수정

- src/components/team/teamCommon/TeamCommonAlert.jsx
- src/components/team/teamCommon/TeamCommonSectionTitle.jsx
- src/components/team/teamCommon/style.jsx
- src/components/team/todo/Todo.jsx
- src/components/team/todo/style.jsx
- src/components/todoEntry/TodoEntry.jsx
- src/components/todoEntry/style.jsx
- src/pages/team/Team.jsx
- 캘린더를 제외한 Todo 화면 구성
- Todo Entry 컴포넌트 구현(관련 버튼은 아직 미구현)
- Team 페이지에서 공통적으로 사용될 Common component 구현
- 더미 데이터 추가해서 Team 페이지와 연결
> [Feat] Todo 구현

- src/components/main/teamPageBtn/TeamPageBtn.jsx
- src/router.jsx
라우팅 작업 준비 중 기존 라우터 수정의 필요를 느낌!
앞으로 팀 상세 페이지는 teamId/:teamId를 타고 가야합니다!
그리고 홈이동에 "/"를 추가해줬습니다
> :ambulance: [router]라우터 긴급 수정

- package-lock.json
- package.json
- src/main.jsx
> :heavy_plus_sign: [dependency] react-redux와 redux/toolkit설치

- src/components/goal/goalColumn/GoalColumn.jsx
- src/components/goal/goalColumn/style.jsx
- src/pages/goal/Goal.jsx
- src/pages/goal/styles.jsx
- src/pages/team/Team.jsx
- src/router.jsx
> :memo: [router] 사이드바 페이지 세팅

- package-lock.json
- package.json
- src/components/team/teamCommon/TeamCommonCheckField.jsx
- src/components/team/teamCommon/style.jsx
- src/components/team/todo/Todo.jsx
FontAwesome 설치
- npm i @fortawesome/fontawesome-svg-core
- npm i @fortawesome/react-fontawesome
- npm i -S @fortawesome/free-solid-svg-icons
- 체크 표시는 추후 업데이트할 것입니다. 현재는 배경 색으로 판단
- 사이드바에서 공통적으로 사용되는 checkbox 컴포넌트로 구현
> ✨ [feat] Fontawesome 패키지 추가, common checkbox 컴포넌트 구현

- src/components/goalDetail/timelineView/TimelineView.jsx
- src/components/goalDetail/todoView/TodoView.jsx
- src/components/goalDetail/todoView/style.jsx
- src/components/team/teamCommon/TeamCommonCommentPost.jsx
- src/components/team/teamCommon/style.jsx
- src/components/todo/todoEntry/TodoEntry.jsx
- src/components/todo/todoEntry/style.jsx
- src/pages/goal/Goal.jsx
- src/pages/goal/styles.jsx
- src/pages/todo/TodoPage.jsx
- src/pages/todo/styles.jsx
- src/router.jsx
- goal 사이드바 네비게이션바 구현 완료
- todoView에서 todoEntry를 사용하려 했지만 구조가 바뀌면서 재사용 불가해짐. 방법을 바꾸어서 추후 업데이트할 예정.
- goal/todo 사이드바에서 공통적으로 사용하는 댓글 입력창을 team common 컴포넌트로 변경
- 기타 자잘한 오류/스타일 수정
> ✨ [feat] goal 사이드바 구현

- package.json
- src/components/goalDetail/todoView/TodoView.jsx
- src/components/todo/todoEntry/TodoEntry.jsx
- src/pages/goal/Goal.jsx
투두 엔트리에 주는 props들을 백엔드와 연동을 대비해 변경해 놓은게 공유가 안되서 생긴 오류입니다
DUMMY_TODOLIST수정과 투두 엔트리에 받는 props를 수정해서 해결했습니다
> 투두엔트리 오류 해결

- src/components/goalDetail/todoView/TodoView.jsx
- src/components/team/todo/Todo.jsx
- src/components/todo/todoEntry/TodoEntry.jsx
- goal 사이드바의 todoView를 통해 todoPage에 접근하면 주소에 goalId이 2번 적히기 때문에 라우팅 오류가 발생
- todoEntry로 isThroughGoal 변수를 함께 보내서 goal을 통해서 todo에 접근하는 건지, 아닌지를 판단해서 라우팅 변경
> 🐛 [fix] todoView를 통해서 todoPage에 접근할 때 url오류 해결

- src/components/goalDetail/timelineView/TimelineView.jsx
- src/components/goalDetail/timelineView/style.jsx
- src/pages/goal/Goal.jsx
> 🚧 goal 사이드바 timeline

- src/components/goalDetail/timelineView/TimelineView.jsx
- src/components/goalDetail/timelineView/style.jsx
- src/components/team/teamCommon/TeamCommonCheckField.jsx
- src/components/team/teamCommon/style.jsx
- src/components/todo/todoEntry/TodoEntry.jsx
- src/components/todo/todoEntry/style.jsx
- timelineView에서 각 todo의 색상에 맞는 체크박스  표시
- todoEntry에서 체크박스를 관리하도록 변경
> ✨ [feat] 체크박스 구현

- src/components/modals/makeModal/MakeModal.jsx
- src/components/todo/todoBtnWrap/TodoBtnWrap.jsx
- src/store/modal/modalSlice.jsx
리덕스에 정보를 담아 제작 모달을 활용하므로 투두 제작을 위한 정보를 썽크를 이용해 담음
> :memo: [todo] todo제작을 위한 정보들 리덕스툴킷 썽크 활용

- src/api/resource/loader.jsx
- src/pages/team/Team.jsx
- src/router.jsx
최대한 상세히 주석으로 설명 달았습니다 나중에 사용하실때 참고 부탁드리고 지금은 비동기가 안되다보니 loader관련된거에 주석을 안달아놓으면 렌더링 자체가 안됩니다 참고부탁드려요
> :memo: [Loader] 로더 함수가 무엇인가

- src/App.jsx
- src/components/goalDetail/timelineView/TimelineView.jsx
- src/components/team/todo/Todo.jsx
- src/pages/goal/Goal.jsx
- goal 사이드바 timeline, todolist API 연결
- 선택한 날짜의 todoList, unfinishedTodo API 연결
- 기본 화면 overflow 속성 변경
- 기타 버그 수정
> ✨ [feat] API 연결

- src/style/theme.js
<사용 방법>
${p=>p.theme.memberColors.(memberId)}
css style 색상은 기존과 동일
> 💄 style: memberId별 색상 코드 추가

- src/api/axios.js
> :memo: [URL] url 전역변수 처리

- src/api/resource/action.jsx
- src/api/resource/loader.jsx
- src/components/team/teamNav/TeamNav.jsx
- src/components/team/todo/Todo.jsx
- src/pages/team/Team.jsx
초기 팀생성 후 멤버추가 예외를 생각하고 짜서 시작하자마자 모달이 뜹니다 양해 탁 ㄱㄱ
> :memo: [Team] 초기 팀 생성과 멤버 추가

- src/components/goalDetail/timelineView/TimelineView.jsx
- src/components/goalDetail/todoView/TodoView.jsx
- src/components/todo/todoEntry/TodoEntry.jsx
- src/components/todo/todoEntry/style.jsx
- todoEntry의 type을 3가지로 정의
1. type: "readonly" -> goal 사이드바의 timelineView
2. type: "routeonly" -> goal 사이드바의 todoView
3. type: "full" -> team 페이지의 오늘 todo, 완료하지 못한 todo
readonly는 체크된 체크박스를 보여주기만 함
routeonly는 라우팅만
full는 라우팅 + 체크 토글 기능
> ✨ [feat] todoEntry 수정 및 적용

- src/components/team/teamNav/TeamNav.jsx
member color 구현
member가 10명을 넘을 경우 색상이 반복
> ✨ feat: member color 구현

- src/api/resource/action.jsx
- src/components/goal/goalColumn/GoalColumn.jsx
- src/components/goal/goalColumn/style.jsx
- src/components/goal/goalSchedule/GoalSchedule.jsx
- src/components/goal/goalSchedule/GoalScheduleContent.jsx
- src/components/modals/makeModal/MakeModal.jsx
- src/components/modals/projectModal/ProjectModal.jsx
- src/components/todo/todoBtnWrap/TodoBtnWrap.jsx
- src/pages/team/Team.jsx
- src/store/goal/goalSlicer.jsx
- src/store/index.jsx
- src/store/modal/modalSlice.jsx
> :memo: 골 투두 팀 멤버 생성 완료
